// Generated by CIRCT firtool-1.71.0
module Foo(	// comb/parity/parity.generic.mlir:3:3
  input  [7:0] a,	// comb/parity/parity.generic.mlir:4:8
  output       res	// comb/parity/parity.mlir:1:31
);

  assign res = ^a;	// comb/parity/parity.generic.mlir:5:10, :6:5
endmodule

