// Generated by CIRCT firtool-1.71.0
module Bar(	// hw/hierpath/hierpath.generic.mlir:4:3
  input  [7:0] a,	// hw/hierpath/hierpath.generic.mlir:5:8
               b,	// hw/hierpath/hierpath.generic.mlir:5:19
  output [7:0] res	// hw/hierpath/hierpath.mlir:1:42
);

  (* dont_merge *)
  reg [7:0] reg_0;	// hw/hierpath/hierpath.generic.mlir:6:10
  assign res = a + b;	// hw/hierpath/hierpath.generic.mlir:7:10, :8:5
endmodule

module Fuu(	// hw/hierpath/hierpath.generic.mlir:10:3
  input  [7:0] a,	// hw/hierpath/hierpath.generic.mlir:11:8
               b,	// hw/hierpath/hierpath.generic.mlir:11:19
  output [7:0] res	// hw/hierpath/hierpath.mlir:6:42
);

  Bar bar (	// hw/hierpath/hierpath.generic.mlir:12:10
    .a   (a),
    .b   (b),
    .res (res)
  );	// hw/hierpath/hierpath.generic.mlir:12:10
endmodule

module Foo();	// hw/hierpath/hierpath.generic.mlir:16:3
endmodule

