// Generated by CIRCT firtool-1.71.0
module Foo(	// comb/replicate/replicate.generic.mlir:3:3
  input  [7:0]  a,	// comb/replicate/replicate.generic.mlir:4:8
  output [15:0] res	// comb/replicate/replicate.mlir:1:31
);

  assign res = {2{a}};	// comb/replicate/replicate.generic.mlir:5:10, :6:5
endmodule

