// Generated by CIRCT firtool-1.71.0
`ifndef _TYPESCOPE_Enums
`define _TYPESCOPE_Enums
  typedef enum bit [1:0] {enum0_A, enum0_B, enum0_C} enum0;
`endif // _TYPESCOPE_Enums
module Foo(	// hw/enum_cmp/enum_cmp.generic.mlir:3:3
  output res	// hw/enum_cmp/enum_cmp.mlir:1:20
);

  wire enum0 _GEN = enum0_A;	// hw/enum_cmp/enum_cmp.generic.mlir:4:10
  assign res = _GEN == _GEN;	// hw/enum_cmp/enum_cmp.generic.mlir:4:10, :6:10, :7:5
endmodule

