// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/assert/assert.generic.mlir:3:3
  input  [7:0] a,	// sv/assert/assert.generic.mlir:4:8
               b,	// sv/assert/assert.generic.mlir:4:19
  output [7:0] res	// sv/assert/assert.mlir:1:42
);

  assign res = a + b;	// sv/assert/assert.generic.mlir:9:10, :10:5
endmodule

