// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/force/force.generic.mlir:3:3
  input        clk,	// sv/force/force.generic.mlir:4:8
  input  [7:0] a,	// sv/force/force.generic.mlir:4:19
               b,	// sv/force/force.generic.mlir:4:30
  output [7:0] res	// sv/force/force.mlir:1:55
);

  reg [7:0] reg_a;	// sv/force/force.generic.mlir:5:10
  reg [7:0] reg_b;	// sv/force/force.generic.mlir:6:10
  initial begin	// sv/force/force.generic.mlir:7:5
    force reg_a = b;	// sv/force/force.generic.mlir:8:7
    force reg_b = a;	// sv/force/force.generic.mlir:9:7
    release reg_a;	// sv/force/force.generic.mlir:10:7
    release reg_b;	// sv/force/force.generic.mlir:11:7
  end // initial
  assign res = reg_a + reg_b;	// sv/force/force.generic.mlir:13:10, :14:10, :15:10, :16:5
endmodule

