// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/struct_field_inout/struct_field_inout.generic.mlir:3:3
  input  [7:0] a,	// sv/struct_field_inout/struct_field_inout.generic.mlir:4:8
               b,	// sv/struct_field_inout/struct_field_inout.generic.mlir:4:19
  output [7:0] res	// sv/struct_field_inout/struct_field_inout.mlir:1:42
);

  struct packed {logic [7:0] a; logic [7:0] b; } reg_0;	// sv/struct_field_inout/struct_field_inout.generic.mlir:6:10
  assign reg_0 = '{a: a, b: b};	// sv/struct_field_inout/struct_field_inout.generic.mlir:5:10, :7:5
  assign res = reg_0.a + reg_0.b;	// sv/struct_field_inout/struct_field_inout.generic.mlir:8:10, :9:10, :10:10, :11:10, :12:10, :13:5
endmodule

