[project]
name = "circt-semantics"
version = "0.1.0"
source = "./src/kproj"

[targets.llvm]
backend = "llvm"
main-file = "main.k"
main-module = "MAIN"
syntax-module = "MLIR-SYNTAX"

[targets.haskell]
backend = "haskell"
main-file = "main.k"
main-module = "MAIN"
syntax-module = "MLIR-SYNTAX"