[project]
name = "circt-semantics"
version = "0.1.0"
source = "./src/kcirct"

[targets.llvm]
backend = "llvm"
main-file = "circt.k"
main-module = "CIRCT"
syntax-module = "MLIR-SYNTAX"

[targets.haskell]
backend = "haskell"
main-file = "circt.k"
main-module = "CIRCT"
syntax-module = "CIRCT-SYNTAX"