// Generated by CIRCT firtool-1.71.0
module Foo(	// hw/array_get/array_get.generic.mlir:3:3
  input  [7:0] a,	// hw/array_get/array_get.generic.mlir:4:8
               b,	// hw/array_get/array_get.generic.mlir:4:19
  output [7:0] res	// hw/array_get/array_get.mlir:1:42
);

  assign res = b - a;	// hw/array_get/array_get.generic.mlir:10:10, :11:5
endmodule

