// Generated by CIRCT firtool-1.71.0
module Foo(	// comb/mul/mul.generic.mlir:3:3
  input  [7:0] a,	// comb/mul/mul.generic.mlir:4:8
               b,	// comb/mul/mul.generic.mlir:4:19
  output [7:0] res	// comb/mul/mul.mlir:1:42
);

  assign res = a * b;	// comb/mul/mul.generic.mlir:5:10, :6:5
endmodule

