// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/verbatim/verbatim.generic.mlir:3:3
  input  [7:0] a,	// sv/verbatim/verbatim.generic.mlir:4:8
               b,	// sv/verbatim/verbatim.generic.mlir:4:19
  output [7:0] res	// sv/verbatim/verbatim.mlir:1:42
);

  ;	// sv/verbatim/verbatim.generic.mlir:5:5
  assign res = a + b;	// sv/verbatim/verbatim.generic.mlir:6:10, :7:5
endmodule

