from __future__ import annotations

import subprocess
from pathlib import Path
from typing import TYPE_CHECKING, TextIO

from .context import _changed_signal, _changed_signal_history

if TYPE_CHECKING:
    from collections.abc import Iterable

    from .context import Signal
    from .model import KimulatorModel

DIFF_VCD = Path(__file__).parent.parent.joinpath('lib').joinpath('diffvcd.py')


def diff(file1: str, file2: str, top1: str, top2: str) -> subprocess.CompletedProcess:
    args = [str(DIFF_VCD), file1, file2, '--top1', top1, '--top2', top2]
    return subprocess.run(args, capture_output=True, text=True)


class KimulatorVCD:
    __vcd_file: TextIO | None = None
    top: KimulatorModel | None = None
    trace_level: int = 0

    def __init__(self, top: KimulatorModel, trace_level: int):
        self.top = top
        self.trace_level = trace_level
        return

    def __del__(self) -> None:
        if self.__vcd_file:
            self.__vcd_file.close()
        return

    def trace(self, model: KimulatorModel, levels: int) -> None:
        self.top = model
        self.trace_level = levels
        return

    def open(self, filename: str) -> None:

        self.__vcd_file = open(filename, 'w')
        # write header
        self.__vcd_file.write('$version Generated by KimulatorVcd $end\n')
        self.__vcd_file.write('$timescale 1ns $end\n\n\n')
        # vcdFile << "$scope module " << top->name << " $end\n";
        self.__vcd_file.write(f'$scope module {self.top.module_name} $end\n')  # type: ignore

        def write_signal(s: Signal, vcd_f: TextIO) -> None:
            if s.signal_type != 'memory':
                if s.signal_type == 'register':
                    vcd_f.write(f'$var reg {s.num_bits} {s.abbrev} {s.name}')
                else:
                    vcd_f.write(f'$var wire {s.num_bits} {s.abbrev} {s.name}')
                if s.num_bits > 1:
                    vcd_f.write(f' [{s.num_bits - 1}:0]')
                vcd_f.write(' $end\n')

        def write_kimulator_model(model: KimulatorModel, vcd_f: TextIO) -> None:
            vcd_f.write(f'$scope module {model.module_name} $end\n')
            for signal in model.signals.values():
                write_signal(signal, vcd_f)
            for sub_model in model.children.values():
                write_kimulator_model(sub_model, vcd_f)
            vcd_f.write('$upscope $end\n')

        for s in self.top.signals.values():  # type: ignore
            write_signal(s, self.__vcd_file)
        write_kimulator_model(self.top, self.__vcd_file)  # type: ignore
        self.__vcd_file.write('$upscope $end\n')
        self.__vcd_file.write('$enddefinitions $end\n')

    def dump(self, t: int) -> None:
        def write_values(signals: Iterable[Signal], vcd_f: TextIO) -> None:
            for signal in signals:
                if signal.num_bits == 1:
                    vcd_f.write(f'{signal.signal_value}{signal.abbrev}\n')
                else:
                    vcd_f.write(f"b{format(signal.signal_value, '0{}b'.format(signal.num_bits))} {signal.abbrev}\n")

        self.__vcd_file.write(f'\n#{t}\n')  # type: ignore
        if t == self.top.context.sim_time:  # type: ignore
            write_values(_changed_signal, self.__vcd_file)  # type: ignore
            _changed_signal.clear()
        else:
            write_values(_changed_signal_history[t], self.__vcd_file)  # type: ignore
            _changed_signal_history[t].clear()
        return

    def close(self) -> None:
        self.__vcd_file.close()  # type: ignore
        return
