// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vaggregate_constant2.cpp"
#include "Vaggregate_constant2__Trace.cpp"
#include "Vaggregate_constant2__Slow.cpp"
#include "Vaggregate_constant2__Syms.cpp"
#include "Vaggregate_constant2__Trace__Slow.cpp"
