// Generated by CIRCT firtool-1.71.0
module Foo(	// comb/extract/extract.generic.mlir:3:3
  input  [7:0] a,	// comb/extract/extract.generic.mlir:4:8
  output [3:0] res	// comb/extract/extract.mlir:1:31
);

  assign res = a[6:3];	// comb/extract/extract.generic.mlir:5:10, :6:5
endmodule

