// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/initial/initial.generic.mlir:3:3
  input  [7:0] a,	// sv/initial/initial.generic.mlir:4:8
               b,	// sv/initial/initial.generic.mlir:4:19
  output [7:0] res	// sv/initial/initial.mlir:1:42
);

  initial	// sv/initial/initial.generic.mlir:5:5
    $info("initial");	// sv/initial/initial.generic.mlir:6:7
  assign res = a + b;	// sv/initial/initial.generic.mlir:8:10, :9:5
endmodule

