// Generated by CIRCT firtool-1.71.0
module Foo(	// comb/concat/concat.generic.mlir:3:3
  input  [7:0]  a,	// comb/concat/concat.generic.mlir:4:8
                b,	// comb/concat/concat.generic.mlir:4:19
  output [15:0] res	// comb/concat/concat.mlir:1:42
);

  assign res = {a, b};	// comb/concat/concat.generic.mlir:5:10, :6:5
endmodule

