// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/ordered/ordered.generic.mlir:3:3
  input  [7:0] a,	// sv/ordered/ordered.generic.mlir:4:8
               b,	// sv/ordered/ordered.generic.mlir:4:19
  output [7:0] res	// sv/ordered/ordered.mlir:1:42
);

  wire [7:0] wire_a = a;	// sv/ordered/ordered.generic.mlir:5:10
  wire [7:0] wire_b = b;	// sv/ordered/ordered.generic.mlir:6:10
  assign res = wire_a + wire_b;	// sv/ordered/ordered.generic.mlir:11:10, :12:10, :13:10, :14:5
endmodule

