// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/macro_def/macro_def.generic.mlir:4:3
  input  [7:0] a,	// sv/macro_def/macro_def.generic.mlir:5:8
               b,	// sv/macro_def/macro_def.generic.mlir:5:19
  output [7:0] res	// sv/macro_def/macro_def.mlir:2:42
);

  `define MACRO 1
  always @*	// sv/macro_def/macro_def.generic.mlir:8:5
    assert(`MACRO);	// sv/macro_def/macro_def.generic.mlir:7:10, :9:7
  assign res = a + b;	// sv/macro_def/macro_def.generic.mlir:11:10, :12:5
endmodule

