// Generated by CIRCT unknown git version
module AddOne(	// adder.mlir:2:3
  input  [7:0] io_a,	// adder.mlir:2:32
  output [7:0] res	// adder.mlir:2:48
);

  assign res = io_a + 8'h1;	// adder.mlir:3:14, :4:10, :5:5
endmodule

module AddTwo(	// adder.mlir:7:3
  input  [7:0] io_a,	// adder.mlir:7:32
  output [7:0] res2	// adder.mlir:7:48
);

  wire [7:0] _i0_res;	// adder.mlir:8:15
  AddOne i0 (	// adder.mlir:8:15
    .io_a (io_a),
    .res  (_i0_res)
  );
  AddOne i1 (	// adder.mlir:9:15
    .io_a (_i0_res),	// adder.mlir:8:15
    .res  (res2)
  );
endmodule

module Adder(	// adder.mlir:12:3
  input  [7:0] io_a,	// adder.mlir:12:23
  output [7:0] res_out2,	// adder.mlir:12:39
               res_out1	// adder.mlir:12:58
);

  wire [7:0] _i0_res2;	// adder.mlir:13:15
  AddTwo i0 (	// adder.mlir:13:15
    .io_a (io_a),
    .res2 (_i0_res2)
  );
  AddOne i2 (	// adder.mlir:14:15
    .io_a (_i0_res2),	// adder.mlir:13:15
    .res  (res_out1)
  );
  assign res_out2 = _i0_res2;	// adder.mlir:13:15, :15:5
endmodule