// Generated by CIRCT firtool-1.71.0
module Foo(	// comb/shrs/shrs.generic.mlir:3:3
  input  [7:0] a,	// comb/shrs/shrs.generic.mlir:4:8
               b,	// comb/shrs/shrs.generic.mlir:4:19
  output [7:0] res	// comb/shrs/shrs.mlir:1:42
);

  assign res = $signed($signed(a) >>> b);	// comb/shrs/shrs.generic.mlir:5:10, :6:5
endmodule

