// Generated by CIRCT firtool-1.71.0
// VCS coverage exclude_file
module memory_4x8(	// seq/firmem_rw/firmem_rw.generic.generic.mlir:4:10
  input  [1:0] R0_addr,
  input        R0_en,
               R0_clk,
  output [7:0] R0_data,
  input  [1:0] RW0_addr,
  input        RW0_en,
               RW0_clk,
               RW0_wmode,
  input  [7:0] RW0_wdata,
  output [7:0] RW0_rdata,
  input  [1:0] W0_addr,
  input        W0_en,
               W0_clk,
  input  [7:0] W0_data
);

  reg [7:0] Memory[0:3];	// seq/firmem_rw/firmem_rw.generic.generic.mlir:4:10
  always @(posedge RW0_clk) begin	// seq/firmem_rw/firmem_rw.generic.generic.mlir:4:10
    if (RW0_en & RW0_wmode & 1'h1)	// seq/firmem_rw/firmem_rw.generic.generic.mlir:4:10
      Memory[RW0_addr] <= RW0_wdata;	// seq/firmem_rw/firmem_rw.generic.generic.mlir:4:10
  end // always @(posedge)
  always @(posedge W0_clk) begin	// seq/firmem_rw/firmem_rw.generic.generic.mlir:4:10
    if (W0_en & 1'h1)	// seq/firmem_rw/firmem_rw.generic.generic.mlir:4:10
      Memory[W0_addr] <= W0_data;	// seq/firmem_rw/firmem_rw.generic.generic.mlir:4:10
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// seq/firmem_rw/firmem_rw.generic.generic.mlir:4:10
    reg [31:0] _RANDOM_MEM;	// seq/firmem_rw/firmem_rw.generic.generic.mlir:4:10
    initial begin	// seq/firmem_rw/firmem_rw.generic.generic.mlir:4:10
      `INIT_RANDOM_PROLOG_	// seq/firmem_rw/firmem_rw.generic.generic.mlir:4:10
      `ifdef RANDOMIZE_MEM_INIT	// seq/firmem_rw/firmem_rw.generic.generic.mlir:4:10
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM_MEM = `RANDOM;	// seq/firmem_rw/firmem_rw.generic.generic.mlir:4:10
          Memory[i[1:0]] = _RANDOM_MEM[7:0];	// seq/firmem_rw/firmem_rw.generic.generic.mlir:4:10
        end
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 8'bx;	// seq/firmem_rw/firmem_rw.generic.generic.mlir:4:10
  assign RW0_rdata = RW0_en & ~RW0_wmode ? Memory[RW0_addr] : 8'bx;	// seq/firmem_rw/firmem_rw.generic.generic.mlir:4:10
endmodule

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module Foo(	// seq/firmem_rw/firmem_rw.generic.generic.mlir:2:3
  input        clk,	// seq/firmem_rw/firmem_rw.generic.generic.mlir:3:8
  input  [7:0] data_in_w,	// seq/firmem_rw/firmem_rw.generic.generic.mlir:3:27
               data_in_rw,	// seq/firmem_rw/firmem_rw.generic.generic.mlir:3:38
  input  [1:0] addr_r,	// seq/firmem_rw/firmem_rw.generic.generic.mlir:3:49
               addr_w,	// seq/firmem_rw/firmem_rw.generic.generic.mlir:3:60
               addr_rw,	// seq/firmem_rw/firmem_rw.generic.generic.mlir:3:71
  input        mode,	// seq/firmem_rw/firmem_rw.generic.generic.mlir:3:82
               enable_r,	// seq/firmem_rw/firmem_rw.generic.generic.mlir:3:93
               enable_w,	// seq/firmem_rw/firmem_rw.generic.generic.mlir:3:104
               enable_rw,	// seq/firmem_rw/firmem_rw.generic.generic.mlir:3:115
  output [7:0] read_out,
               rw_out
);

  memory_4x8 memory_ext (	// seq/firmem_rw/firmem_rw.generic.generic.mlir:4:10
    .R0_addr   (addr_r),
    .R0_en     (enable_r),
    .R0_clk    (clk),
    .R0_data   (read_out),
    .RW0_addr  (addr_rw),
    .RW0_en    (enable_rw),
    .RW0_clk   (clk),
    .RW0_wmode (mode),
    .RW0_wdata (data_in_rw),
    .RW0_rdata (rw_out),
    .W0_addr   (addr_w),
    .W0_en     (enable_w),
    .W0_clk    (clk),
    .W0_data   (data_in_w)
  );	// seq/firmem_rw/firmem_rw.generic.generic.mlir:4:10
endmodule

