// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/bpassign/bpassign.generic.mlir:3:3
  input        clk,	// sv/bpassign/bpassign.generic.mlir:4:8
  input  [7:0] a,	// sv/bpassign/bpassign.generic.mlir:4:19
               b,	// sv/bpassign/bpassign.generic.mlir:4:30
  output [7:0] res	// sv/bpassign/bpassign.mlir:1:55
);

  reg [7:0] reg_0;	// sv/bpassign/bpassign.generic.mlir:5:10
  always @*	// sv/bpassign/bpassign.generic.mlir:6:5
    reg_0 = a;	// sv/bpassign/bpassign.generic.mlir:7:7
  assign res = reg_0 + b;	// sv/bpassign/bpassign.generic.mlir:9:10, :10:10, :11:5
endmodule

