// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/if/if.generic.mlir:3:3
  input        clk,	// sv/if/if.generic.mlir:4:8
  input  [7:0] a,	// sv/if/if.generic.mlir:4:19
               b,	// sv/if/if.generic.mlir:4:30
  output [7:0] res	// sv/if/if.mlir:1:54
);

  always @(posedge clk)	// sv/if/if.generic.mlir:6:5
    $info("hitIf");	// sv/if/if.generic.mlir:8:9
  assign res = a + b;	// sv/if/if.generic.mlir:12:10, :13:5
endmodule

