// Generated by CIRCT firtool-1.71.0
module Foo(	// hw/aggregate_constant3/aggregate_constant3.generic.mlir:3:3
  input  [1:0]  a,	// hw/aggregate_constant3/aggregate_constant3.generic.mlir:4:8
  input  [63:0] b,	// hw/aggregate_constant3/aggregate_constant3.generic.mlir:4:19
  output [63:0] res	// hw/aggregate_constant3/aggregate_constant3.mlir:1:43
);

  assign res = b - 64'h1;	// hw/aggregate_constant3/aggregate_constant3.generic.mlir:8:10, :9:5
endmodule

