// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/array_index_inout/array_index_inout.generic.mlir:3:3
  input  [7:0] a,	// sv/array_index_inout/array_index_inout.generic.mlir:4:8
               b,	// sv/array_index_inout/array_index_inout.generic.mlir:4:19
  output [7:0] res	// sv/array_index_inout/array_index_inout.mlir:1:42
);

  reg [1:0][7:0] reg_0;	// sv/array_index_inout/array_index_inout.generic.mlir:6:10
  assign reg_0 = {{a}, {b}};	// sv/array_index_inout/array_index_inout.generic.mlir:5:10, :7:5
  assign res = reg_0[8'h0] + reg_0[8'h1];	// sv/array_index_inout/array_index_inout.generic.mlir:10:10, :11:10, :12:10, :13:10, :14:10, :15:5
endmodule

