// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/case/case.generic.mlir:3:3
  input        clk,	// sv/case/case.generic.mlir:4:8
  input  [7:0] a,	// sv/case/case.generic.mlir:4:19
               b,	// sv/case/case.generic.mlir:4:30
  output [7:0] res	// sv/case/case.mlir:1:55
);

  initial begin	// sv/case/case.generic.mlir:5:5
    case (clk)	// sv/case/case.generic.mlir:6:7
      1'b0:
        $error("zero");	// sv/case/case.generic.mlir:7:9
      1'b1:
        $error("one");	// sv/case/case.generic.mlir:9:9
    endcase	// sv/case/case.generic.mlir:6:7
  end // initial
  assign res = a + b;	// sv/case/case.generic.mlir:12:10, :13:5
endmodule

