// Generated by CIRCT firtool-1.71.0
module Foo(	// hw/output/output.generic.mlir:3:3
  input  [7:0] a,	// hw/output/output.generic.mlir:4:8
               b,	// hw/output/output.generic.mlir:4:19
  output [7:0] res	// hw/output/output.mlir:1:42
);

  assign res = a + b;	// hw/output/output.generic.mlir:5:10, :6:5
endmodule

