// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/indexed_part_select_inout/indexed_part_select_inout.generic.mlir:3:3
  input  [7:0] a,	// sv/indexed_part_select_inout/indexed_part_select_inout.generic.mlir:4:8
               b,	// sv/indexed_part_select_inout/indexed_part_select_inout.generic.mlir:4:19
  output [7:0] res	// sv/indexed_part_select_inout/indexed_part_select_inout.mlir:1:42
);

  reg [3:0][7:0] reg_0;	// sv/indexed_part_select_inout/indexed_part_select_inout.generic.mlir:6:10
  assign reg_0 = {{a}, {b}, {a}, {b}};	// sv/indexed_part_select_inout/indexed_part_select_inout.generic.mlir:5:10, :7:5
  assign res = reg_0[8'h0 +: 2][1'h0] + reg_0[8'h0 +: 2][1'h1];	// sv/indexed_part_select_inout/indexed_part_select_inout.generic.mlir:9:10, :10:10, :13:10, :14:10, :15:10, :16:5
endmodule

