// Generated by CIRCT firtool-1.71.0
module Foo(	// hw/aggregate_constant/aggregate_constant.generic.mlir:3:3
  output struct packed {logic [1:0] a; logic [1:0] b; logic [1:0] c; } res	// hw/aggregate_constant/aggregate_constant.mlir:1:20
);

  assign res = '{a: 2'h1, b: 2'h2, c: 2'h3};	// hw/aggregate_constant/aggregate_constant.generic.mlir:4:10, :5:5
endmodule

