// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/generate/generate.generic.mlir:3:3
  input  [7:0] a,	// sv/generate/generate.generic.mlir:4:8
               b,	// sv/generate/generate.generic.mlir:4:19
  output [7:0] res	// sv/generate/generate.mlir:1:42
);

  generate
  begin: test
    case ("case_1")
    endcase
    case ("case_2")
    endcase
  end: test
  endgenerate
  assign res = a + b;	// sv/generate/generate.generic.mlir:9:10, :10:5
endmodule

