// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/fwrite/fwrite.generic.mlir:3:3
  input  [7:0] a,	// sv/fwrite/fwrite.generic.mlir:4:8
               b,	// sv/fwrite/fwrite.generic.mlir:4:19
  output [7:0] res	// sv/fwrite/fwrite.mlir:1:42
);

  initial	// sv/fwrite/fwrite.generic.mlir:6:5
    $fwrite(32'h1, "format string");	// sv/fwrite/fwrite.generic.mlir:5:10, :7:7
  assign res = a + b;	// sv/fwrite/fwrite.generic.mlir:9:10, :10:5
endmodule

