// Generated by CIRCT firtool-1.71.0
module Foo(	// comb/mux/mux.generic.mlir:3:3
  input        a,	// comb/mux/mux.generic.mlir:4:8
  input  [7:0] b,	// comb/mux/mux.generic.mlir:4:19
               c,	// comb/mux/mux.generic.mlir:4:30
  output [7:0] res	// comb/mux/mux.mlir:1:52
);

  assign res = a ? b : c;	// comb/mux/mux.generic.mlir:5:10, :6:5
endmodule

