// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/constantZ/constantZ.generic.mlir:3:3
  input        clk,	// sv/constantZ/constantZ.generic.mlir:4:8
  input  [7:0] a,	// sv/constantZ/constantZ.generic.mlir:4:19
               b,	// sv/constantZ/constantZ.generic.mlir:4:30
  output [7:0] res	// sv/constantZ/constantZ.mlir:1:55
);

  assign res = 8'bz + b;	// sv/constantZ/constantZ.generic.mlir:5:10, :6:10, :7:5
endmodule

