#!/bin/bash

# K-CIRCT Verification Demo Commands
# Shows example kprove commands for manual verification

echo "=== K-CIRCT Verification Demo Commands ==="
echo ""
echo "This script demonstrates the kprove commands used for verification."
echo "These commands are extracted from the automated verification scripts."
echo ""

VERIFICATION_DIR="$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")"

echo "Working directory: $VERIFICATION_DIR"
echo ""

echo "=== 1. Constant Folding Verification Commands ==="
echo ""

echo "# Compile the constant folding specification:"
echo "kompile -v specs/constant_folding_spec.k \\"
echo "    --syntax-module CONSTANT-FOLDING-SYNTAX \\"
echo "    --main-module CONSTANT-FOLDING-SPEC \\"
echo "    -o results/constant_folding/constant-folding-kompiled"
echo ""

echo "# Verify original module produces 8:"
echo "kprove specs/constant_folding_spec.k \\"
echo "    --definition results/constant_folding/constant-folding-kompiled \\"
echo "    --spec-module CONSTANT-FOLDING-SPEC \\"
echo "    --claim \"ConstantFoldingOriginal-claim\" \\"
echo "    --output-file results/constant_folding/original.log \\"
echo "    --verbose"
echo ""

echo "# Verify optimized module produces 8:"
echo "kprove specs/constant_folding_spec.k \\"
echo "    --definition results/constant_folding/constant-folding-kompiled \\"
echo "    --spec-module CONSTANT-FOLDING-SPEC \\"
echo "    --claim \"ConstantFoldingOptimized-claim\" \\"
echo "    --output-file results/constant_folding/optimized.log \\"
echo "    --verbose"
echo ""

echo "# Verify equivalence between original and optimized:"
echo "kprove specs/constant_folding_spec.k \\"
echo "    --definition results/constant_folding/constant-folding-kompiled \\"
echo "    --spec-module CONSTANT-FOLDING-SPEC \\"
echo "    --claim \"equivalence-claim\" \\"
echo "    --output-file results/constant_folding/equivalence.log \\"
echo "    --verbose"
echo ""

echo "=== 2. Arithmetic Safety Verification Commands ==="
echo ""

echo "# Compile the arithmetic safety specification:"
echo "kompile -v specs/arithmetic_safety_spec.k \\"
echo "    --syntax-module ARITHMETIC-SAFETY-SYNTAX \\"
echo "    --main-module ARITHMETIC-SAFETY-SPEC \\"
echo "    -o results/arithmetic_safety/arithmetic-safety-kompiled"
echo ""

echo "# Verify general overflow detection property:"
echo "kprove specs/arithmetic_safety_spec.k \\"
echo "    --definition results/arithmetic_safety/arithmetic-safety-kompiled \\"
echo "    --spec-module ARITHMETIC-SAFETY-SPEC \\"
echo "    --claim \"general-overflow-claim\" \\"
echo "    --output-file results/arithmetic_safety/general_overflow.log \\"
echo "    --verbose"
echo ""

echo "# Verify no overflow case (sum < 16):"
echo "kprove specs/arithmetic_safety_spec.k \\"
echo "    --definition results/arithmetic_safety/arithmetic-safety-kompiled \\"
echo "    --spec-module ARITHMETIC-SAFETY-SPEC \\"
echo "    --claim \"no-overflow-claim\" \\"
echo "    --output-file results/arithmetic_safety/no_overflow.log \\"
echo "    --verbose"
echo ""

echo "# Verify overflow case (sum >= 16):"
echo "kprove specs/arithmetic_safety_spec.k \\"
echo "    --definition results/arithmetic_safety/arithmetic-safety-kompiled \\"
echo "    --spec-module ARITHMETIC-SAFETY-SPEC \\"
echo "    --claim \"overflow-case-claim\" \\"
echo "    --output-file results/arithmetic_safety/overflow_case.log \\"
echo "    --verbose"
echo ""

echo "=== 3. Bounded Model Checking Examples ==="
echo ""

echo "# Example concrete test cases for 4-bit adder:"
echo "# No overflow: a=7, b=8 -> sum=15, overflow=0"
echo "# No overflow: a=0, b=15 -> sum=15, overflow=0"
echo "# Overflow: a=15, b=15 -> sum=14, overflow=1"  
echo "# Overflow: a=8, b=8 -> sum=0, overflow=1"
echo ""

echo "=== 4. Verification with Specific Inputs ==="
echo ""

echo "# To verify with specific concrete values, modify the K claims:"
echo "# Replace symbolic variables A:Int, B:Int with concrete values"
echo "# Example for a=5, b=3:"
echo "#   <args>"
echo "#       ListItem ( bits ( 5 , 4 ) : i4 )"
echo "#       ListItem ( bits ( 3 , 4 ) : i4 )"
echo "#   </args>"
echo "#   ensures ?Result ==Int 8"
echo ""

echo "=== 5. Debug and Analysis Commands ==="
echo ""

echo "# Run K with additional debugging:"
echo "export K_OPTS=\"--verbose --debug\""
echo "kprove <specification> <options>"
echo ""

echo "# Check compiled definition:"
echo "klist results/*/compiled-definition/compiled.txt"
echo ""

echo "# Analyze kore output:"
echo "cat results/*/verification.log | grep -A 10 -B 10 \"claim\""
echo ""

echo "=== 6. Manual Execution for Development ==="
echo ""

echo "# Step-by-step manual verification process:"
echo "cd $VERIFICATION_DIR"
echo "mkdir -p results/{constant_folding,arithmetic_safety}"
echo ""
echo "# 1. Compile specification"
echo "kompile -v specs/constant_folding_spec.k --main-module CONSTANT-FOLDING-SPEC"
echo ""
echo "# 2. Run individual claim"
echo "kprove specs/constant_folding_spec.k --claim <claim-name>"
echo ""
echo "# 3. Check results"
echo "echo \$?  # 0 = success, non-zero = failure"
echo ""

echo "=== Usage Notes ==="
echo ""
echo "- All paths are relative to the verification directory"
echo "- Claims are defined in the K specification files"
echo "- Use --verbose for detailed output during development"
echo "- Check exit codes: 0 = verified, non-zero = failed/error"
echo "- Generated logs contain detailed proof traces"