// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/exit/exit.generic.mlir:3:3
  input        clk,	// sv/exit/exit.generic.mlir:4:8
  input  [7:0] a,	// sv/exit/exit.generic.mlir:4:19
               b,	// sv/exit/exit.generic.mlir:4:30
  output [7:0] res	// sv/exit/exit.mlir:1:55
);

  always @(posedge clk)	// sv/exit/exit.generic.mlir:6:5
    $exit;	// sv/exit/exit.generic.mlir:7:7
  assign res = a + b;	// sv/exit/exit.generic.mlir:9:10, :10:5
endmodule

