// Generated by CIRCT firtool-1.71.0
module Foo(	// hw/bitcast/bitcast.generic.mlir:3:3
  input  [7:0]  a,	// hw/bitcast/bitcast.generic.mlir:4:8
                b,	// hw/bitcast/bitcast.generic.mlir:4:19
  output [15:0] res	// hw/bitcast/bitcast.mlir:1:42
);

  wire struct packed {logic [7:0] a; logic [7:0] b; } _GEN = '{a: a, b: b};	// hw/bitcast/bitcast.generic.mlir:5:10
  assign res = /*cast(bit[15:0])*/_GEN;	// hw/bitcast/bitcast.generic.mlir:5:10, :6:10, :7:5
endmodule

