// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/cover_concurrent/cover_concurrent.generic.mlir:3:3
  input        clk,	// sv/cover_concurrent/cover_concurrent.generic.mlir:4:8
  input  [7:0] a,	// sv/cover_concurrent/cover_concurrent.generic.mlir:4:19
               b,	// sv/cover_concurrent/cover_concurrent.generic.mlir:4:30
  output [7:0] res	// sv/cover_concurrent/cover_concurrent.mlir:1:55
);

  cover property (@(posedge clk) 1'h1);	// sv/cover_concurrent/cover_concurrent.generic.mlir:5:10, :6:5
  assign res = a + b;	// sv/cover_concurrent/cover_concurrent.generic.mlir:7:10, :8:5
endmodule

