// Generated by CIRCT firtool-1.71.0
module Foo(	// hw/union_create/union_create.generic.mlir:3:3
  input  [7:0] a,	// hw/union_create/union_create.generic.mlir:4:8
               b,	// hw/union_create/union_create.generic.mlir:4:19
  output [7:0] res	// hw/union_create/union_create.mlir:1:42
);

  wire union packed {logic [7:0] foo;logic [7:0] bar;} _GEN = a;	// hw/union_create/union_create.generic.mlir:5:10
  wire union packed {logic [7:0] foo;logic [7:0] bar;} _GEN_0 = b;	// hw/union_create/union_create.generic.mlir:7:10
  assign res = _GEN.foo + _GEN_0.bar;	// hw/union_create/union_create.generic.mlir:5:10, :6:10, :7:10, :8:10, :9:10, :10:5
endmodule

