// Generated by CIRCT firtool-1.71.0
module Foo(	// comb/extract2/extract2.generic.mlir:2:3
  input  [31:0] a,	// comb/extract2/extract2.generic.mlir:3:8
  output [3:0]  b7,
  output [31:0] b8,
  output [7:0]  b9,
  output [2:0]  b10,
  output [1:0]  b11,
  output        b12,
  output [3:0]  b13,
  output [2:0]  b14,
  output [3:0]  b15,
                b16,
                b17,
  output        b18
);

  wire [69:0] _GEN = {{2{a}}, 6'h0} - 70'h1FFF7F800000000000;	// comb/extract2/extract2.generic.mlir:5:10, :6:10, :7:10
  assign b7 = _GEN[3:0];	// comb/extract2/extract2.generic.mlir:7:10, :8:10, :20:5
  assign b8 = _GEN[35:4];	// comb/extract2/extract2.generic.mlir:7:10, :9:10, :20:5
  assign b9 = _GEN[43:36];	// comb/extract2/extract2.generic.mlir:7:10, :10:10, :20:5
  assign b10 = _GEN[46:44];	// comb/extract2/extract2.generic.mlir:7:10, :11:11, :20:5
  assign b11 = _GEN[48:47];	// comb/extract2/extract2.generic.mlir:7:10, :12:11, :20:5
  assign b12 = _GEN[49];	// comb/extract2/extract2.generic.mlir:7:10, :13:11, :20:5
  assign b13 = _GEN[53:50];	// comb/extract2/extract2.generic.mlir:7:10, :14:11, :20:5
  assign b14 = _GEN[56:54];	// comb/extract2/extract2.generic.mlir:7:10, :15:11, :20:5
  assign b15 = _GEN[60:57];	// comb/extract2/extract2.generic.mlir:7:10, :16:11, :20:5
  assign b16 = _GEN[64:61];	// comb/extract2/extract2.generic.mlir:7:10, :17:11, :20:5
  assign b17 = _GEN[68:65];	// comb/extract2/extract2.generic.mlir:7:10, :18:11, :20:5
  assign b18 = _GEN[69];	// comb/extract2/extract2.generic.mlir:7:10, :19:11, :20:5
endmodule

