// Generated by CIRCT firtool-1.71.0
module Foo(	// hw/array_concat/array_concat.generic.mlir:3:3
  input  [7:0] a,	// hw/array_concat/array_concat.generic.mlir:4:8
               b,	// hw/array_concat/array_concat.generic.mlir:4:19
  output [7:0] res	// hw/array_concat/array_concat.mlir:1:42
);

  assign res = b + a;	// hw/array_concat/array_concat.generic.mlir:12:10, :13:5
endmodule

