// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/stop/stop.generic.mlir:3:3
  input        clk,	// sv/stop/stop.generic.mlir:4:8
  input  [7:0] a,	// sv/stop/stop.generic.mlir:4:19
               b,	// sv/stop/stop.generic.mlir:4:30
  output [7:0] res	// sv/stop/stop.mlir:1:55
);

  always @*	// sv/stop/stop.generic.mlir:5:5
    $stop(2);	// sv/stop/stop.generic.mlir:6:7
  assign res = a + b;	// sv/stop/stop.generic.mlir:8:10, :9:5
endmodule

