// Generated by CIRCT firtool-1.71.0
module Foo(	// comb/mods/mods.generic.mlir:3:3
  input  [7:0] a,	// comb/mods/mods.generic.mlir:4:8
               b,	// comb/mods/mods.generic.mlir:4:19
  output [7:0] res	// comb/mods/mods.mlir:1:42
);

  assign res = $signed(a) % $signed(b);	// comb/mods/mods.generic.mlir:5:10, :6:5
endmodule

