// Generated by CIRCT firtool-1.71.0
module Foo(	// seq/from_clock/from_clock.generic.mlir:2:3
  input  clk,	// seq/from_clock/from_clock.generic.mlir:3:8
  output res
);

  assign res = clk;	// seq/from_clock/from_clock.generic.mlir:5:5
endmodule

