// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/cover/cover.generic.mlir:3:3
  input  [7:0] a,	// sv/cover/cover.generic.mlir:4:8
               b,	// sv/cover/cover.generic.mlir:4:19
  output [7:0] res	// sv/cover/cover.mlir:1:42
);

  initial	// sv/cover/cover.generic.mlir:6:5
    cover(1'h1);	// sv/cover/cover.generic.mlir:5:10, :7:7
  assign res = a + b;	// sv/cover/cover.generic.mlir:9:10, :10:5
endmodule

