// Generated by CIRCT firtool-1.71.0
// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

module Foo(	// seq/firreg2/firreg2.generic.mlir:5:3
  input        clk,	// seq/firreg2/firreg2.generic.mlir:6:8
               reset,	// seq/firreg2/firreg2.generic.mlir:6:27
  output [7:0] res,	// seq/firreg2/firreg2.mlir:1:55
               res2,	// seq/firreg2/firreg2.mlir:1:68
               res3	// seq/firreg2/firreg2.mlir:1:82
);

  reg  [7:0] reg_port;	// seq/firreg2/firreg2.generic.mlir:7:10
  wire [7:0] _GEN = reg_port + 8'h1;	// seq/firreg2/firreg2.generic.mlir:7:10, :10:10
  reg  [7:0] reg_port2;	// seq/firreg2/firreg2.generic.mlir:12:10
  always @(posedge clk) begin	// seq/firreg2/firreg2.generic.mlir:6:8
    if (reset) begin	// seq/firreg2/firreg2.generic.mlir:6:8
      reg_port <= 8'h0;	// seq/firreg2/firreg2.generic.mlir:7:10
      reg_port2 <= 8'h0;	// seq/firreg2/firreg2.generic.mlir:12:10
    end
    else begin	// seq/firreg2/firreg2.generic.mlir:6:8
      reg_port <= _GEN;	// seq/firreg2/firreg2.generic.mlir:7:10, :10:10
      reg_port2 <= _GEN;	// seq/firreg2/firreg2.generic.mlir:10:10, :12:10
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// seq/firreg2/firreg2.generic.mlir:5:3
    `ifdef FIRRTL_BEFORE_INITIAL	// seq/firreg2/firreg2.generic.mlir:5:3
      `FIRRTL_BEFORE_INITIAL	// seq/firreg2/firreg2.generic.mlir:5:3
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// seq/firreg2/firreg2.generic.mlir:5:3
    initial begin	// seq/firreg2/firreg2.generic.mlir:5:3
      `ifdef INIT_RANDOM_PROLOG_	// seq/firreg2/firreg2.generic.mlir:5:3
        `INIT_RANDOM_PROLOG_	// seq/firreg2/firreg2.generic.mlir:5:3
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// seq/firreg2/firreg2.generic.mlir:5:3
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// seq/firreg2/firreg2.generic.mlir:5:3
        reg_port = _RANDOM[/*Zero width*/ 1'b0][10:3];	// seq/firreg2/firreg2.generic.mlir:5:3, :7:10
        reg_port2 = _RANDOM[/*Zero width*/ 1'b0][10:3];	// seq/firreg2/firreg2.generic.mlir:5:3, :7:10, :12:10
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// seq/firreg2/firreg2.generic.mlir:5:3
      `FIRRTL_AFTER_INITIAL	// seq/firreg2/firreg2.generic.mlir:5:3
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign res = _GEN;	// seq/firreg2/firreg2.generic.mlir:10:10, :13:5
  assign res2 = reg_port;	// seq/firreg2/firreg2.generic.mlir:7:10, :13:5
  assign res3 = reg_port2;	// seq/firreg2/firreg2.generic.mlir:12:10, :13:5
endmodule

