// Generated by CIRCT firtool-1.71.0
module Wrap(	// sv/xmr_ref/xmr_ref.generic.mlir:6:5
  input  [7:0] xx,	// sv/xmr_ref/xmr_ref.generic.mlir:7:10
  output [7:0] res	// foo.mlir:1:33
);

  (* dont_merge *)
  reg  [7:0] y;	// sv/xmr_ref/xmr_ref.generic.mlir:8:14
  (* dont_merge *)
  wire [7:0] z;	// sv/xmr_ref/xmr_ref.generic.mlir:9:14
  assign y = xx;	// sv/xmr_ref/xmr_ref.generic.mlir:10:9
  assign res = xx;	// sv/xmr_ref/xmr_ref.generic.mlir:11:9
endmodule

module Swap(	// sv/xmr_ref/xmr_ref.generic.mlir:14:5
  input  [7:0] xx,	// sv/xmr_ref/xmr_ref.generic.mlir:15:10
               yy,	// sv/xmr_ref/xmr_ref.generic.mlir:15:21
  output [7:0] res1,	// foo.mlir:8:45
               res2	// foo.mlir:8:59
);

  Wrap wrap (	// sv/xmr_ref/xmr_ref.generic.mlir:16:14
    .xx  (xx),
    .res (res2)
  );	// sv/xmr_ref/xmr_ref.generic.mlir:16:14
  assign res1 = yy;	// sv/xmr_ref/xmr_ref.generic.mlir:17:9
endmodule

module Foo(	// sv/xmr_ref/xmr_ref.generic.mlir:29:5
  input  [7:0] a,	// sv/xmr_ref/xmr_ref.generic.mlir:30:10
               b,	// sv/xmr_ref/xmr_ref.generic.mlir:30:21
  output [7:0] res	// foo.mlir:16:42
);

  wire [7:0] _swap2_res1;	// sv/xmr_ref/xmr_ref.generic.mlir:32:16
  Swap swap1 (	// sv/xmr_ref/xmr_ref.generic.mlir:31:16
    .xx   (a),
    .yy   (b),
    .res1 (/* unused */),
    .res2 (/* unused */)
  );	// sv/xmr_ref/xmr_ref.generic.mlir:31:16
  Swap swap2 (	// sv/xmr_ref/xmr_ref.generic.mlir:32:16
    .xx   (a),
    .yy   (b),
    .res1 (_swap2_res1),
    .res2 (/* unused */)
  );	// sv/xmr_ref/xmr_ref.generic.mlir:32:16
  assign res = _swap2_res1 + Foo.swap1.wrap.y;	// sv/xmr_ref/xmr_ref.generic.mlir:32:16, :33:14, :34:14, :35:14, :36:9
endmodule

