// Generated by CIRCT firtool-1.71.0
module Wrap(	// sv/xmr/xmr.generic.mlir:6:5
  input  [7:0] x,	// sv/xmr/xmr.generic.mlir:7:14
  output [7:0] res	// foo.mlir:1:32
);

  (* dont_merge *)
  reg  [7:0] y;	// sv/xmr/xmr.generic.mlir:8:18
  (* dont_merge *)
  wire [7:0] z;	// sv/xmr/xmr.generic.mlir:9:18
  assign res = x;	// sv/xmr/xmr.generic.mlir:10:13
endmodule

module Swap(	// sv/xmr/xmr.generic.mlir:13:5
  input  [7:0] x,	// sv/xmr/xmr.generic.mlir:14:14
               y,	// sv/xmr/xmr.generic.mlir:14:25
  output [7:0] res1,	// foo.mlir:7:43
               res2	// foo.mlir:7:57
);

  Wrap wrap (	// sv/xmr/xmr.generic.mlir:15:18
    .x   (x),
    .res (res2)
  );	// sv/xmr/xmr.generic.mlir:15:18
  assign res1 = y;	// sv/xmr/xmr.generic.mlir:16:13
endmodule

module Foo(	// sv/xmr/xmr.generic.mlir:19:5
  input  [7:0] a,	// sv/xmr/xmr.generic.mlir:20:14
               b,	// sv/xmr/xmr.generic.mlir:20:25
  output [7:0] result	// foo.mlir:12:42
);

  wire [7:0] _swap2_res2;	// sv/xmr/xmr.generic.mlir:22:20
  Swap swap1 (	// sv/xmr/xmr.generic.mlir:21:20
    .x    (a),
    .y    (b),
    .res1 (/* unused */),
    .res2 (/* unused */)
  );	// sv/xmr/xmr.generic.mlir:21:20
  Swap swap2 (	// sv/xmr/xmr.generic.mlir:22:20
    .x    (a),
    .y    (b),
    .res1 (/* unused */),
    .res2 (_swap2_res2)
  );	// sv/xmr/xmr.generic.mlir:22:20
  assign result = _swap2_res2 + $root.swap1.wrap.y;	// sv/xmr/xmr.generic.mlir:22:20, :23:18, :24:18, :25:18, :26:13
endmodule

