// Generated by CIRCT firtool-1.71.0
module Foo(	// hw/struct_inject/struct_inject.generic.mlir:3:3
  input  [7:0] a,	// hw/struct_inject/struct_inject.generic.mlir:4:8
               b,	// hw/struct_inject/struct_inject.generic.mlir:4:19
  output [7:0] res	// hw/struct_inject/struct_inject.mlir:1:42
);

  assign res = a + b;	// hw/struct_inject/struct_inject.generic.mlir:9:10, :10:5
endmodule

