// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/macro_decl/macro_decl.generic.mlir:4:3
  input  [7:0] a,	// sv/macro_decl/macro_decl.generic.mlir:5:8
               b,	// sv/macro_decl/macro_decl.generic.mlir:5:19
  output [7:0] res	// sv/macro_decl/macro_decl.mlir:2:42
);

  always @*	// sv/macro_decl/macro_decl.generic.mlir:7:5
    assert(`1);	// sv/macro_decl/macro_decl.generic.mlir:6:10, :8:7
  assign res = a + b;	// sv/macro_decl/macro_decl.generic.mlir:10:10, :11:5
endmodule

