// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/alwaysff/alwaysff.generic.mlir:3:3
  input        clk,	// sv/alwaysff/alwaysff.generic.mlir:4:8
  input  [7:0] a,	// sv/alwaysff/alwaysff.generic.mlir:4:19
               b,	// sv/alwaysff/alwaysff.generic.mlir:4:30
  output [7:0] result	// sv/alwaysff/alwaysff.mlir:1:55
);

  always_ff @(posedge clk)	// sv/alwaysff/alwaysff.generic.mlir:5:5
    $error("hello");	// sv/alwaysff/alwaysff.generic.mlir:6:7
  assign result = a + b;	// sv/alwaysff/alwaysff.generic.mlir:9:10, :10:5
endmodule

