// Generated by CIRCT firtool-1.71.0
module Foo(	// hw/constant/constant.generic.mlir:3:3
  input  [7:0] a,	// hw/constant/constant.generic.mlir:4:8
  output [7:0] res	// hw/constant/constant.mlir:1:31
);

  assign res = a + 8'h2A;	// hw/constant/constant.generic.mlir:5:10, :6:10, :7:5
endmodule

