// Generated by CIRCT firtool-1.71.0
module Foo(	// hw/constant/constant.generic.mlir:3:3
  output [7:0] res	// hw/constant/constant.mlir:1:20
);

  assign res = 8'h2A;	// hw/constant/constant.generic.mlir:4:10, :5:5
endmodule

