// Generated by CIRCT firtool-1.71.0
module Foo(	// hw/struct_explode/struct_explode.generic.mlir:3:3
  input  [7:0] a,	// hw/struct_explode/struct_explode.generic.mlir:4:8
               b,	// hw/struct_explode/struct_explode.generic.mlir:4:19
  output [7:0] res	// hw/struct_explode/struct_explode.mlir:1:42
);

  assign res = a + b;	// hw/struct_explode/struct_explode.generic.mlir:7:10, :8:5
endmodule

