// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/always/always.generic.mlir:3:3
  input        clk,	// sv/always/always.generic.mlir:4:8
  input  [7:0] a,	// sv/always/always.generic.mlir:4:19
               b,	// sv/always/always.generic.mlir:4:30
  output [7:0] result	// sv/always/always.mlir:1:55
);

  always @(posedge clk)	// sv/always/always.generic.mlir:5:5
    $warning("hello");	// sv/always/always.generic.mlir:6:7
  always @*	// sv/always/always.generic.mlir:8:5
    $info("world");	// sv/always/always.generic.mlir:9:7
  assign result = a + b;	// sv/always/always.generic.mlir:11:10, :12:5
endmodule

