// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/info/info.generic.mlir:3:3
  input        clk,	// sv/info/info.generic.mlir:4:8
  input  [7:0] a,	// sv/info/info.generic.mlir:4:19
               b,	// sv/info/info.generic.mlir:4:30
  output [7:0] result	// sv/info/info.mlir:1:55
);

  always @(posedge clk)	// sv/info/info.generic.mlir:5:5
    $info("world");	// sv/info/info.generic.mlir:6:7
  assign result = a + b;	// sv/info/info.generic.mlir:8:10, :9:5
endmodule

