// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/verbatim_expr/verbatim_expr.generic.mlir:3:3
  input  [7:0] a,	// sv/verbatim_expr/verbatim_expr.generic.mlir:4:8
               b,	// sv/verbatim_expr/verbatim_expr.generic.mlir:4:19
  output [7:0] res	// sv/verbatim_expr/verbatim_expr.mlir:1:42
);

  assign res = a + b;	// sv/verbatim_expr/verbatim_expr.generic.mlir:6:10, :7:5
endmodule

