// Generated by CIRCT firtool-1.71.0
module Foo(	// hw/aggregate_constant2/aggregate_constant2.generic.mlir:3:3
  input  [1:0] a,	// hw/aggregate_constant2/aggregate_constant2.generic.mlir:4:8
  input  [7:0] b,	// hw/aggregate_constant2/aggregate_constant2.generic.mlir:4:19
  output [7:0] res	// hw/aggregate_constant2/aggregate_constant2.mlir:1:42
);

  wire [3:0][7:0] _GEN = '{8'hFF, 8'h0, 8'h1, 8'h2};	// hw/aggregate_constant2/aggregate_constant2.generic.mlir:5:10
  assign res = _GEN[a] + b;	// hw/aggregate_constant2/aggregate_constant2.generic.mlir:5:10, :6:10, :7:10, :8:5
endmodule

