// Generated by CIRCT firtool-1.71.0
module Foo(	// hw/struct_extract/struct_extract.generic.mlir:3:3
  input  [7:0] a,	// hw/struct_extract/struct_extract.generic.mlir:4:8
               b,	// hw/struct_extract/struct_extract.generic.mlir:4:19
  output [7:0] res	// hw/struct_extract/struct_extract.mlir:1:42
);

  assign res = a + b;	// hw/struct_extract/struct_extract.generic.mlir:8:10, :9:5
endmodule

