// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/assume/assume.generic.mlir:3:3
  input  [7:0] a,	// sv/assume/assume.generic.mlir:4:8
               b,	// sv/assume/assume.generic.mlir:4:19
  output [7:0] res	// sv/assume/assume.mlir:1:42
);

  reg [7:0] reg_a;	// sv/assume/assume.generic.mlir:5:10
  reg [7:0] reg_b;	// sv/assume/assume.generic.mlir:6:10
  assign reg_a = a;	// sv/assume/assume.generic.mlir:7:5
  assign reg_b = b;	// sv/assume/assume.generic.mlir:8:5
  assign res = reg_a + reg_b;	// sv/assume/assume.generic.mlir:9:10, :10:10, :11:10, :12:5
endmodule

