// Generated by CIRCT firtool-1.71.0
module Bar(	// hw/instance/instance.generic.mlir:4:3
  input  [7:0] a,	// hw/instance/instance.generic.mlir:5:8
               b,	// hw/instance/instance.generic.mlir:5:19
  output [7:0] res	// hw/instance/instance.mlir:1:42
);

  assign res = a + b;	// hw/instance/instance.generic.mlir:6:10, :7:5
endmodule

module Foo(	// hw/instance/instance.generic.mlir:9:3
  input  [7:0] a,	// hw/instance/instance.generic.mlir:10:8
               b,	// hw/instance/instance.generic.mlir:10:19
  output [7:0] res	// hw/instance/instance.mlir:5:42
);

  Bar bar (	// hw/instance/instance.generic.mlir:11:10
    .a   (a),
    .b   (b),
    .res (res)
  );	// hw/instance/instance.generic.mlir:11:10
endmodule

