// Generated by CIRCT firtool-1.71.0
module AddOne(	// hw/instance/instance.generic.mlir:6:3
  input  [7:0] io_a,	// hw/instance/instance.generic.mlir:7:8
  output [7:0] res	// hw/instance/instance.mlir:2:48
);

  assign res = io_a + 8'h1;	// hw/instance/instance.generic.mlir:8:10, :9:10, :10:5
endmodule

module AddTwo(	// hw/instance/instance.generic.mlir:12:3
  input  [7:0] io_a,	// hw/instance/instance.generic.mlir:13:8
  output [7:0] res2	// hw/instance/instance.mlir:7:48
);

  wire [7:0] _i3_res;	// hw/instance/instance.generic.mlir:14:10
  AddOne i3 (	// hw/instance/instance.generic.mlir:14:10
    .io_a (io_a),
    .res  (_i3_res)
  );	// hw/instance/instance.generic.mlir:14:10
  AddOne i1 (	// hw/instance/instance.generic.mlir:15:10
    .io_a (_i3_res),	// hw/instance/instance.generic.mlir:14:10
    .res  (res2)
  );	// hw/instance/instance.generic.mlir:15:10
endmodule

module Foo(	// hw/instance/instance.generic.mlir:18:3
  input  [7:0] io_a,	// hw/instance/instance.generic.mlir:19:8
  output [7:0] res_out2,	// hw/instance/instance.mlir:12:37
               res_out1	// hw/instance/instance.mlir:12:56
);

  wire [7:0] _i0_res2;	// hw/instance/instance.generic.mlir:20:10
  AddTwo i0 (	// hw/instance/instance.generic.mlir:20:10
    .io_a (io_a),
    .res2 (_i0_res2)
  );	// hw/instance/instance.generic.mlir:20:10
  AddOne i2 (	// hw/instance/instance.generic.mlir:21:10
    .io_a (_i0_res2),	// hw/instance/instance.generic.mlir:20:10
    .res  (res_out1)
  );	// hw/instance/instance.generic.mlir:21:10
  assign res_out2 = _i0_res2;	// hw/instance/instance.generic.mlir:20:10, :22:5
endmodule

