// Generated by CIRCT firtool-1.71.0
module Foo(	// comb/icmp/icmp.generic.mlir:3:3
  input  [7:0] a,	// comb/icmp/icmp.generic.mlir:4:8
               b,	// comb/icmp/icmp.generic.mlir:4:19
  output       res	// comb/icmp/icmp.mlir:1:42
);

  assign res = a == b;	// comb/icmp/icmp.generic.mlir:5:10, :6:5
endmodule

