// Generated by CIRCT firtool-1.71.0
module Foo(	// comb/icmp/icmp.generic.mlir:2:3
  input  [7:0] a,	// comb/icmp/icmp.generic.mlir:3:8
               b,	// comb/icmp/icmp.generic.mlir:3:19
  output       res,
               res1,
               res6,
               res8,
               res9
);

  assign res = a == b;	// comb/icmp/icmp.generic.mlir:4:10, :9:5
  assign res1 = a != b;	// comb/icmp/icmp.generic.mlir:5:10, :9:5
  assign res6 = a < b;	// comb/icmp/icmp.generic.mlir:6:10, :9:5
  assign res8 = a > b;	// comb/icmp/icmp.generic.mlir:7:10, :9:5
  assign res9 = a >= b;	// comb/icmp/icmp.generic.mlir:8:10, :9:5
endmodule

