// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/assume_concurrent/assume_concurrent.generic.mlir:3:3
  input        clk,	// sv/assume_concurrent/assume_concurrent.generic.mlir:4:8
  input  [7:0] a,	// sv/assume_concurrent/assume_concurrent.generic.mlir:4:19
               b,	// sv/assume_concurrent/assume_concurrent.generic.mlir:4:30
  output [7:0] res	// sv/assume_concurrent/assume_concurrent.mlir:1:55
);

  assign res = a + b;	// sv/assume_concurrent/assume_concurrent.generic.mlir:7:10, :8:5
endmodule

