// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/logic/logic.generic.mlir:3:3
  input  [7:0] a,	// sv/logic/logic.generic.mlir:4:8
               b,	// sv/logic/logic.generic.mlir:4:19
  output [7:0] res	// sv/logic/logic.mlir:1:42
);

  logic [7:0] logic_a = a;	// sv/logic/logic.generic.mlir:5:10
  logic [7:0] logic_b = b;	// sv/logic/logic.generic.mlir:6:10
  assign res = logic_a + logic_b;	// sv/logic/logic.generic.mlir:9:10, :10:10, :11:10, :12:5
endmodule

