// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/alwayscomb/alwayscomb.generic.mlir:3:3
  input        clk,	// sv/alwayscomb/alwayscomb.generic.mlir:4:8
  input  [7:0] a,	// sv/alwayscomb/alwayscomb.generic.mlir:4:19
               b,	// sv/alwayscomb/alwayscomb.generic.mlir:4:30
  output [7:0] result	// sv/alwayscomb/alwayscomb.mlir:1:55
);

  always_comb	// sv/alwayscomb/alwayscomb.generic.mlir:5:5
    $error("hello");	// sv/alwayscomb/alwayscomb.generic.mlir:6:7
  assign result = a + b;	// sv/alwayscomb/alwayscomb.generic.mlir:8:10, :9:5
endmodule

