from __future__ import annotations

import json
import subprocess
from dataclasses import dataclass
from functools import cached_property
from pathlib import Path
from typing import TextIO


@dataclass
class Signal:
    name: str
    abbrev: str
    num_bits: int
    type: str


@dataclass
class Module:
    name: str
    signals: list[Signal]
    children: list[Module]


class Abbrev:
    _rest: int = 0

    @classmethod
    def gen(cls) -> str:
        cls._rest += 1
        t: int = cls._rest
        abbrev = ''
        while t != 0:
            c = (t % 84) + 33
            if c >= ord('0'):
                c += 10
            abbrev += chr(int(c))
            t //= 84
        return abbrev


class KVCD:
    __vcd_file: TextIO
    _mlir_path: Path
    _state_json_path: Path
    abbrevs: dict[str, str]
    time: int
    time_scale: str
    filename: str

    def __init__(
        self,
        vcd_path: Path,
        mlir_path: Path,
        state_json_path: Path | None = None,
        time_scale: str = '1ns',
    ):
        self.__vcd_file = open(vcd_path, 'w')
        self._mlir_path = mlir_path
        self._state_json_path = state_json_path
        if self._state_json_path is None:
            self._state_json_path = mlir_path.parent / 'state.json'
            self.generate_json()
        self.time = 0
        self.time_scale = time_scale
        self.abbrevs = {}
        self._init()
        return

    def __del__(self) -> None:
        if self.__vcd_file:
            self.__vcd_file.close()
        return

    def generate_json(self) -> subprocess.CompletedProcess:
        """Generate state JSON from MLIR"""
        args = ['arcilator', str(self._mlir_path), '--state-file=' + str(self._state_json_path), '--observe-ports']
        return subprocess.run(args, stdout=subprocess.PIPE)

    @cached_property
    def modules(self) -> tuple[Module, dict[str, Module]]:
        modules: dict[str, Module] = {}

        def _add_to_module(signal: Signal, modules: dict[str, Module]) -> None:
            module_hierarchy = signal.name.split('/')[:-1]
            prev_module: Module | None = None
            idx = 0
            while idx < len(module_hierarchy):
                module_name = '/'.join(module_hierarchy[: idx + 1])
                if module_name not in modules:
                    modules[module_name] = Module(module_name, [], [])
                if prev_module and modules[module_name] not in prev_module.children:
                    prev_module.children.append(modules[module_name])
                prev_module = modules[module_name]
                idx += 1
            assert signal not in prev_module.signals
            prev_module.signals.append(signal)

        with open(self._state_json_path, 'r') as f:
            state_json = json.load(f)
        assert len(state_json) == 1, 'state.json should only have one module'
        module = state_json[0]
        top_module_name = module['name']
        states = module['states']

        for state in states:
            signal_name = f"{top_module_name}/{state['name']}"
            signal_abbrev = Abbrev.gen()
            self.abbrevs[signal_name] = signal_abbrev
            signal = Signal(
                name=signal_name,
                abbrev=signal_abbrev,
                num_bits=state['numBits'],
                type=state['type'],
            )
            _add_to_module(signal, modules)

        return modules[top_module_name], modules

    def _init(self) -> None:
        # write header
        self.__vcd_file.write('$version Generated by KCIRCT $end\n')
        self.__vcd_file.write(f'$timescale {self.time_scale} $end\n\n\n')
        # vcdFile << "$scope module " << top->name << " $end\n";
        self.__vcd_file.write(f'$scope module {self.modules[0].name} $end\n')  # type: ignore

        def write_signal(s: Signal, vcd_f: TextIO) -> None:
            if s.type != 'memory':
                if s.type == 'register':
                    vcd_f.write(f'$var reg {s.num_bits} {s.abbrev} {s.name}')
                else:
                    vcd_f.write(f'$var wire {s.num_bits} {s.abbrev} {s.name}')
                if s.num_bits > 1:
                    vcd_f.write(f' [{s.num_bits - 1}:0]')
                vcd_f.write(' $end\n')

        def write_kimulator_model(model: Module, vcd_f: TextIO) -> None:
            vcd_f.write(f'$scope module {model.name} $end\n')
            for signal in model.signals:
                write_signal(signal, vcd_f)
            for sub_model in model.children:
                write_kimulator_model(sub_model, vcd_f)
            vcd_f.write('$upscope $end\n')

        for s in self.modules[0].signals:  # type: ignore
            write_signal(s, self.__vcd_file)
        write_kimulator_model(self.modules[0], self.__vcd_file)  # type: ignore
        self.__vcd_file.write('$upscope $end\n')
        self.__vcd_file.write('$enddefinitions $end\n')

    def write_values(self, ports: dict[str, tuple[int, int]]) -> None:
        for signal_name, signal_values in ports.items():
            if signal_values[1] == 1:
                self.__vcd_file.write(f'{signal_values[0]}{self.abbrevs[signal_name]}\n')
            else:
                self.__vcd_file.write(
                    f"b{format(signal_values[0], '0{}b'.format(signal_values[1]))} {self.abbrevs[signal_name]}\n"
                )

    def dump(self, ports: dict[str, tuple[int, int]]) -> None:
        self.__vcd_file.write(f'\n#{self.time}\n')
        self.write_values(ports)
        return

    # def dump(self, t: int) -> None:
    #     def write_values(signals: Iterable[Signal], vcd_f: TextIO) -> None:
    #         for signal in signals:
    #             if signal.num_bits == 1:
    #                 vcd_f.write(f'{signal.signal_value}{signal.abbrev}\n')
    #             else:
    #                 vcd_f.write(f"b{format(signal.signal_value, '0{}b'.format(signal.num_bits))} {signal.abbrev}\n")

    #     self.__vcd_file.write(f'\n#{t}\n')  # type: ignore
    #     if t == self.top.context.sim_time:  # type: ignore
    #         write_values(_changed_signal, self.__vcd_file)  # type: ignore
    #         _changed_signal.clear()
    #     else:
    #         write_values(_changed_signal_history[t], self.__vcd_file)  # type: ignore
    #         _changed_signal_history[t].clear()
    #     return

    def close(self) -> None:
        self.__vcd_file.close()  # type: ignore
        return
