// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/indexed_part_select/indexed_part_select.generic.mlir:3:3
  input  [7:0] a,	// sv/indexed_part_select/indexed_part_select.generic.mlir:4:8
               b,	// sv/indexed_part_select/indexed_part_select.generic.mlir:4:19
  output [7:0] res	// sv/indexed_part_select/indexed_part_select.mlir:1:42
);

  assign res = a[8'h0 +: 8] + b[8'h0 +: 8];	// sv/indexed_part_select/indexed_part_select.generic.mlir:5:10, :6:10, :7:10, :8:10, :9:5
endmodule

