// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/sv_wire/sv_wire.generic.mlir:3:3
  input  [7:0] a,	// sv/sv_wire/sv_wire.generic.mlir:4:8
               b,	// sv/sv_wire/sv_wire.generic.mlir:4:19
  output [7:0] res	// sv/sv_wire/sv_wire.mlir:1:42
);

  assign res = a + b;	// sv/sv_wire/sv_wire.generic.mlir:11:10, :12:5
endmodule

