from .model import KimulatorModel
from .context import Signal
from typing import Iterable
from .context import _changed_signal_history, _changed_signal
from pathlib import Path
import subprocess

DIFF_VCD = Path(__file__).parent.parent.joinpath('lib').joinpath('diffvcd.py')


def diff(file1: str, file2: str, top1: str, top2: str) -> subprocess.CompletedProcess:
    args = [DIFF_VCD, file1, file2, '--top1', top1, '--top2', top2]
    return subprocess.run(args, capture_output=True, text=True)


class KimulatorVCD:
    __vcdFile = None
    top: KimulatorModel = None
    trace_level: int = 0

    def __init__(self, top: KimulatorModel, trace_level: int):
        self.top = top
        self.trace_level = trace_level
        return

    def __del__(self):
        if self.__vcdFile:
            self.__vcdFile.close()
        return

    def trace(self, model: KimulatorModel, levels: int):
        self.top = model
        self.trace_level = levels
        return

    def open(self, filename: str):

        self.__vcdFile = open(filename, 'w')
        # write header
        self.__vcdFile.write("$version Generated by KimulatorVcd $end\n")
        self.__vcdFile.write("$timescale 1ns $end\n\n\n")
        # vcdFile << "$scope module " << top->name << " $end\n";
        self.__vcdFile.write(f"$scope module {self.top.module_name} $end\n")

        def write_signal(s: Signal, vcd_f):
            if s.signal_type != 'memory':
                if s.signal_type == 'register':
                    vcd_f.write(f"$var reg {s.num_bits} {s.abbrev} {s.name}")
                else:
                    vcd_f.write(f"$var wire {s.num_bits} {s.abbrev} {s.name}")
                if s.num_bits > 1:
                    vcd_f.write(f" [{s.num_bits - 1}:0]")
                vcd_f.write(" $end\n")

        def write_kimulator_model(model: KimulatorModel, vcd_f):
            vcd_f.write(f"$scope module {model.module_name} $end\n")
            for signal in model.signals.values():
                write_signal(signal, vcd_f)
            for sub_model in model.children:
                write_kimulator_model(sub_model, vcd_f)
            vcd_f.write("$upscope $end\n")

        for s in self.top.signals.values():
            write_signal(s, self.__vcdFile)
        write_kimulator_model(self.top, self.__vcdFile)
        self.__vcdFile.write("$upscope $end\n")
        self.__vcdFile.write("$enddefinitions $end\n")

    def dump(self, t: int):
        def write_values(signals: Iterable[Signal], vcd_f):
            for signal in signals:
                if signal.num_bits == 1:
                    vcd_f.write(f"{signal.signal_value}{signal.abbrev}\n")
                else:
                    vcd_f.write(f"b{format(signal.signal_value, '0{}b'.format(signal.num_bits))} {signal.abbrev}\n")

        self.__vcdFile.write(f"\n#{t}\n")
        if t == self.top.context.sim_time:
            write_values(_changed_signal, self.__vcdFile)
            _changed_signal.clear()
        else:
            write_values(_changed_signal_history[t], self.__vcdFile)
            _changed_signal_history[t].clear()
        return

    def close(self):
        self.__vcdFile.close()
        return
