// Generated by CIRCT firtool-1.71.0
module Foo(	// sv/readmem/readmem.generic.mlir:3:3
  input  [7:0] a,	// sv/readmem/readmem.generic.mlir:4:8
               b,	// sv/readmem/readmem.generic.mlir:4:19
  output [7:0] res	// sv/readmem/readmem.mlir:1:42
);

  reg [7:0] file;	// sv/readmem/readmem.generic.mlir:5:10
  initial	// sv/readmem/readmem.generic.mlir:6:5
    $readmemb("input.txt", file);	// sv/readmem/readmem.generic.mlir:7:7
  assign res = a + b;	// sv/readmem/readmem.generic.mlir:9:10, :10:5
endmodule

