// Generated by CIRCT firtool-1.71.0
module Foo(	// hw/wire/wire.generic.mlir:3:3
  output [7:0] res	// hw/wire/wire.mlir:1:20
);

  wire [7:0] myWire = 8'h0;	// hw/wire/wire.generic.mlir:4:10, :5:10
  assign res = myWire;	// hw/wire/wire.generic.mlir:5:10, :6:5
endmodule

